/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface DataSchemasCorpusJson {
  corpus_id: string;
  name: string;
  domain: string;
  description: string;
  language: string[];
  document_type: string;
  size: number;
  /**
   * @minItems 0
   */
  parent_corpora_id: string[];
}
