/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Corpora {
  corpora: {
    corpus_id?: string;
    corpus_name?: string;
    genre?: string;
    description?: string;
    language?: string[];
    document_type?: string;
    document_count?: number;
    /**
     * @minItems 0
     */
    parent_corpora_id?: string[];
    [k: string]: unknown;
  }[];
}
