/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Papers {
  papers: {
    paper_id: string;
    open_alex_id?: string;
    paper_title: string;
    /**
     * @minItems 1
     */
    authors: [string, ...string[]];
    year: number;
    doi?: string;
    paper_link: string;
    annotations: {
      dataset_id: string;
      annotation_task: (
        | "Argument Component Segmentation"
        | "Argument Component Type Classification"
        | "Argument Relation Identification"
        | "Argument Relation Type Classification"
        | "Claim Extraction with Stance Classification"
        | "Maximal Argument Quality Assessment"
        | "Minimal Argument Quality Assessment"
        | "Argument Type Identification"
        | "Argument Summarization"
        | "Other"
        | "None"
      )[];
      description: string[];
      annotator_type: string;
      agreement_type: string;
      agreement_score:
        | number
        | [number, number]
        | ("Not reported" | "None")
        | {
            [k: string]: number;
          };
      accessibility: "Free" | "Upon Request" | "Paid" | "Unavailable";
      release_link?: string;
      release_name: string;
      subset: number | string;
    }[];
  }[];
}
