/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Papers {
  papers: {
    paper_id: string;
    paper_title: string;
    /**
     * @minItems 1
     */
    authors: [string, ...string[]];
    description: string;
    year: number;
    doi?: string;
    paper_link?: string;
    annotations: {
      corpus_id: string;
      annotation_task: (
        | "ACS"
        | "ACTC"
        | "CE"
        | "CEPE"
        | "ABAM"
        | "CDCD"
        | "CDED"
        | "CESC"
        | "ARI"
        | "ARTC"
        | "ACRE"
        | "Other"
      )[];
      description: string;
      annotator_count: number;
      /**
       * @minItems 1
       */
      annotator_type: [
        "Author" | "Expert" | "Student" | "Crowd" | "Other",
        ...("Author" | "Expert" | "Student" | "Crowd" | "Other")[]
      ];
      agreement_type: "Cohen's Kappa" | "Fleiss' Kappa" | "Krippendorff's Alpha" | "Percent Agreement" | "Other";
      agreement_score?: number;
      accessibility: "Free" | "Upon Request" | "Paid" | "Unavailable";
      perspectivist: boolean;
      corpus_link?: string;
    }[];
  }[];
}
